config/routes.rb
FleetTracker::Application.routes.draw do
  match 'fleets/leave' => 'fleets#leave', :as => :leave
  resources :fleets do
    resources :reports
  end
  resources :users

  match 'fleets/:id/join' => 'fleets#join', :as => :join
  match 'about' => 'pages#about'
  match 'env' => 'pages#env'
  match 'ping' => 'users#ping'
  match 'users/:id/tag' => 'tags#create_tag', :as => :create_tag, :via => :post
  match 'users/:id/tag' => 'tags#remove_tag', :as => :remove_tag, :via => :delete
  match 'users/:id/tag' => 'tags#add_tag', :as => :add_tag
  resources :tags do
    get :autocomplete_tag_text, :on => :collection
  end

  root :to => "fleets#index"

end

app/models/fleet.rb
# == Schema Information
#
# Table name: fleets
#
#  id                  :integer         not null, primary key
#  title               :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  scope               :integer
#  display_pilot_count :boolean
#  display_fc_info     :boolean
#  fc                  :string(255)
#  xo                  :string(255)
#  created_by          :string(255)
#  corp_name           :string(255)
#  alliance_name       :string(255)
#  direct_access       :boolean
#  users_count         :integer
#  deleted_at          :time
#

class Fleet < ActiveRecord::Base
  acts_as_random_id
  acts_as_paranoid
  validates_presence_of :title, :scope
  
  has_many :users
  has_many :reports
  
  OPEN = 3
  ALLIANCE = 2
  CORP = 2
  PRIVATE = 1
  
  # scope :open, where(:scope => OPEN) # Unused currently and overrides existing open method
  
  def self.new_from_user(user)
    fleet = new(:display_pilot_count => true, 
                :display_fc_info => true,
                :scope => ALLIANCE,
                :direct_access => true)
    if user
      fleet.title = "#{user.char_name}'s Fleet"
      fleet.fc = user.char_name
      fleet.xo = user.char_name
      fleet.created_by = user.char_name
      fleet.corp_name = user.corp_name
      fleet.alliance_name = user.alliance_name
      if fleet.alliance_name.blank?
        fleet.scope = CORP # use corp instead of alliance
      end
    end
    return fleet
  end
  
  def self.visible(user)
    where("scope = #{OPEN} or (scope = #{ALLIANCE} and alliance_name = ?) or (scope = #{CORP} and corp_name = ?) or created_by = ? or fc = ? or xo = ? or id = ? and deleted = false", 
          user.alliance_name, user.corp_name, user.char_name, user.char_name, user.char_name, user.fleet_id)
  end  

  def summarize
    # Calculate summmary
    system = {}
    users.each do |user|
      if system[user.solar_system_name].nil?
        system[user.solar_system_name] = [user]
      else
        system[user.solar_system_name] << user
      end
    end
    # Sort based on number of pilots in each system
    sorted_systems = system.sort {|a,b| a[1].count <=> b[1].count}
    sorted_systems.reverse!
    return sorted_systems
  end
  
  def scope_to_s
    map = ["Private", "Corp", "Alliance", "Anyone"]
    return map[scope]
  end
  
  def new_reports?(after = 0)
    self.reports.where("updated_at > ?", Time.at(after.to_i + 1)).count > 0
  end
  
  def user_changes_since?(after = 0)
    self.users.where("changed_at > ?", Time.at(after.to_i + 1)).count > 0
  end
  
  def admin?(user)
    return false if user.nil?
    return true if user.global_admin?
    case user.char_name
    when self.fc, self.xo, self.created_by
      return true
    else
      return false
    end
  end
  
  def access_by?(user)
    return true if user.global_admin?
    return false if self.deleted?
    return true if self.direct_access
    return false if user.nil?
    return true if user.fleet == self
    return true if self.admin?(user)
    case self.scope
    when OPEN
      return true
    when ALLIANCE
      return self.alliance_name == user.alliance_name
    when CORP
      return self.corp_name == user.corp_name
    end
  end
  
  def purge_users
    users = self.users.abandoned
    users.map(&:leave_fleet)
    return users
  end
  
  scope :empty, lambda {
    #select("fleets.*,count(users.id)").
    #joins("LEFT JOIN users ON fleets.id = users.fleet_id").
    #group("fleets.id,fleet.title, fleet.created_at, fleet.updated_at, fleet.scope, fleet.display_pilot_count, fleet.display_fc_info, fleet.fc, fleet.xo, fleet.created_by, fleet.corp_name, fleet.alliance_name, fleet.direct_access").
    #having("count(users.id)=0")
    #select("fleets.*, (select count(users.id) from users where fleets.id = users.fleet_id) as user_count").
    #having("user_count=0")
    where("users_count=0")
  }
  
  def self.purge
    Fleet.empty.map(&:delete)
  end
  
end

app/controllers/fleets_controller.rb
class FleetsController < ApplicationController
  before_filter :get_current_user#, :except => [:index, :show]
  before_filter :require_igb, :only => [:index, :join, :leave, :new, :create]
  before_filter :check_fleet_id, :only => [:show, :join, :purge, :edit, :update, :destroy]
  # TODO Find a way to do this as a background task instead
  before_filter :purge_fleets, :only => [:index]
  
  # GET /fleets
  # GET /fleets.xml
  def index
    @fleets = ((@current_user && @current_user.global_admin?) ? Fleet.with_deleted : Fleet.visible(@current_user))

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fleets }
    end
  end

  # def purge
  #   @fleet = Fleet.find(params[:id])
  #   @users = @fleet.purge_users
  # end
  
  # GET /fleets/1
  # GET /fleets/1.xml
  # GET /fleets/1.js
  def show
    @fleet = Fleet.find(params[:id])
    
    you_hacker unless @fleet.access_by?(@current_user)
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fleet }
      format.js
    end
  end

  # GET /fleets/1/join
  def join
    @fleet = Fleet.find(params[:id])
    if @current_user.join_fleet(@fleet)
      redirect_to @fleet, :notice => "Fleet joined"
    else
      redirect_to root_path, :error => "Failed to join fleet"
    end
  end

  # GET /fleets/leave
  def leave
    if @current_user.leave_fleet
      redirect_to root_path, :notice => "Fleet cleared"
    else
      redirect_to root_path, :error => "Failed to leave fleet"
    end
  end

  # GET /fleets/new
  # GET /fleets/new.xml
  def new
    @fleet = Fleet.new_from_user(@current_user)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fleet }
    end
  end

  # GET /fleets/1/edit
  def edit
    @fleet = Fleet.find(params[:id])
  end

  # POST /fleets
  # POST /fleets.xml
  def create
    @fleet = Fleet.new(params[:fleet])

    respond_to do |format|
      if @fleet.save
        @current_user.join_fleet(@fleet) # auto join after creation
        format.html { redirect_to(@fleet, :notice => 'Fleet was successfully created.') }
        format.xml  { render :xml => @fleet, :status => :created, :location => @fleet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fleet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fleets/1
  # PUT /fleets/1.xml
  def update
    @fleet = Fleet.find(params[:id])

    respond_to do |format|
      if @fleet.update_attributes(params[:fleet])
        format.html { redirect_to(@fleet, :notice => 'Fleet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fleet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fleets/1
  # DELETE /fleets/1.xml
  def destroy
    @fleet = Fleet.find(params[:id])
    @fleet.destroy

    respond_to do |format|
      format.html { redirect_to(fleets_url) }
      format.xml  { head :ok }
    end
  end

  protected
  
  def check_fleet_id
    if(@current_user.global_admin?)
      you_hacker unless Fleet.with_deleted.exists?(params[:id])
    else
      you_hacker unless Fleet.exists?(params[:id])
    end
  end
  
  def you_hacker    
    redirect_to root_path, :notice => "You hacker!"
  end
  
  def purge_fleets
    User.purge
    Fleet.purge
  end
  
end

app/helpers/fleets_helper.rb
module FleetsHelper

  def section(title, id=title.parameterize, default="minus")
    content_tag :div, :class => "toggle", :id => "#{id}-handle" do
      # tag :div, :class => default, :id => "#{id}-icon"
      content_tag :a, title, :class => "section-head"
    end
  end
  
  def summarize(fleet)
    output = ""
    first_line = true
    fleet.summarize.each do |sys|
      item = "#{sys[1].count} in #{sys[0]}"
      if first_line == true
        item += " (#{(sys[1].count.to_f / fleet.users.count.to_f * 100).round}%)" 
        first_line = false
      end
      count = 0
      first = true
      sys[1].each do |user|
        if user.tag
          item += " [ " if first
          item += "#{user.tag.text} (#{user.char_name}) "
          first = false
        else
          count = count + 1
        end
      end
      item += "+ #{pluralize(count, "other")} " unless (first || count == 0)
      item += "]" unless first
      output += content_tag :li, item
    end
    return output.html_safe
  end

end

app/views/fleets/_details.html.haml
= section "Details", "details", "plus"
.section#details
  = render 'details_inner'

app/views/fleets/_details_inner.html.haml
%small
  Created by #{@fleet.created_by}
  = timeago(@fleet.created_at)
%br/
FC: #{@fleet.fc}<br/>
XO: #{@fleet.xo}<br/>
Visible to: #{@fleet.scope_to_s}<br/>
Direct access: #{@fleet.direct_access}<br/>
- if @fleet.admin?(@current_user)
  #{link_to 'Edit', edit_fleet_path(@fleet)}

app/views/fleets/_form.html.haml
= form_for(@fleet) do |f|
  - if @fleet.errors.any?
    #error_explanation
      %h3= "#{pluralize(@fleet.errors.count, "error")} prohibited this fleet from being saved:"
      %ul
        - @fleet.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :title, :placeholder => "Title"
  .field
    = f.check_box :display_pilot_count
    = f.label :display_pilot_count
  .field
    = f.check_box :display_fc_info
    = f.label :display_fc_info, "Display FC info"
  .field
    = f.label :fc, "FC"
    = f.text_field :fc
    (Exact match allows admin)
  .field
    = f.label :xo, "XO"
    = f.text_field :xo
    (Exact match allows admin)
  .field
    = f.label :scope, "Visible to"
    %br/
    #{f.radio_button :scope, 0} Private<br/>
    #{f.radio_button :scope, 1} Corporation [#{@fleet.corp_name}]<br/>
    #{f.radio_button :scope, 2} Alliance &lt;#{@fleet.alliance_name}&gt;<br/>
    #{f.radio_button :scope, 3} Anyone<br/>
  .field
    = f.check_box :direct_access
    = f.label :direct_access, "Allow direct access with fleet URL"
    (Required to view out-of-game)
  = f.hidden_field :created_by
  = f.hidden_field :corp_name
  = f.hidden_field :alliance_name
  .actions
    = f.submit

app/views/fleets/_pilots.html.haml
= section "Pilots"
- unless @fleet.users.empty?
  .section.pilots#pilots
    = render @fleet.users

app/views/fleets/_recon.html.haml
- if @current_user
  = section("Recon")
  .section.recon
    = render 'recon_form'

app/views/fleets/_recon_form.html.haml
= form_for [@fleet,@fleet.reports.build] do |f|
  = f.hidden_field :reds, :value => 0
  = f.hidden_field :neutrals, :value => 0
  .actions= f.submit "System is clear"
= form_for [@fleet,@fleet.reports.build] do |f|
  .field
    /= f.text_field :reds, :size => 3
    - [0,1,2,3,4,5,6,7,8,9,10,20,30,40,50].each do |i|
      = form_for [@fleet,@fleet.reports.build] do |f|
        = f.hidden_field :reds, :value => i
        = f.submit i
    = f.label :reds
  .field
    /= f.text_field :neutrals, :size => 3
    - [0,1,2,3,4,5,6,7,8,9,10,20,30,40,50].each do |i|
      = form_for [@fleet,@fleet.reports.build] do |f|
        = f.hidden_field :neutrals, :value => i
        = f.submit i
    = f.label :neutrals

app/views/fleets/_reports.html.haml
= section("Reports")
%table.section.reports#reports 
  = render @fleet.reports

app/views/fleets/_scouts.html.haml
= section("Scouts, Skirmishers, and Squads, oh my!")
- style= (@fleet.users.tagged.count == 0 ? "display:none;" : "")
%ul.section.scouts#scouts(style="#{style}")
  = render 'scouts_inner'

app/views/fleets/_scouts_inner.html.haml
- @fleet.users.tagged.each do |user|
  %li= "#{user.tag.text} (#{user.char_name}) in #{user.solar_system_name}"
  -#    = "+ #{pluralize(count, "other")}" unless first
- if @fleet.users.tagged.count == 0
  %li Tag some pilots to have them show up here

app/views/fleets/_summary.html.haml
= section("Summary")
%ul.section.summary#summary
  = summarize(@fleet)

app/views/fleets/edit.html.haml
%h2 Editing fleet
= render 'form'
#{link_to 'Show', @fleet} |
= link_to 'Back', fleets_path

app/views/fleets/igb_required.html.haml
%h2 IGB Required
%p Eve Ranch's Fleet Tracker lets you track and visualize where the members of your fleet are during a roam, in text or map form. Keep track of your scouts, and watch out for stragglers. Scouts can add their recon reports directly as well.
%p You must be using the Eve in-game-browser to list or create fleets. If you're already in a fleet, copy the direct fleet URL while in-game and view the fleet directly out of game.

app/views/fleets/index.html.haml
- if @fleets.empty?
  .not_available No fleets available to you
- else  
  %table.fleets
    - @fleets.each do |fleet|
      %tr[fleet]
        - pilot_count = fleet.users.count
        %td= link_to fleet.title, fleet_path(fleet)
        %td
          = link_to 'View', fleet_path(fleet)
          %br/
          = link_to 'Edit', edit_fleet_path(fleet) if fleet.admin?(@current_user)
        %td  
          - if @current_user.in_fleet?(fleet)
            = link_to 'Leave', leave_path
          - else
            = link_to 'Join', join_url(:id => fleet.id)
          %br/
          - if fleet.admin?(@current_user)
            = link_to 'Delete', fleet, :confirm => 'Are you sure?', :method => :delete
        %td= pluralize(pilot_count,"pilot") if fleet.display_pilot_count
        %td
          = "FC: #{fleet.fc}" if fleet.display_fc_info && !fleet.fc.blank?
          - unless fleet.fc.blank? || fleet.xo.blank?
            %br/ 
          = "XO: #{fleet.xo}" if (fleet.display_fc_info && !fleet.xo.blank?)
        %td
          %small
            = "Created by #{fleet.created_by}"
            %br/
            = "#{time_ago_in_words(fleet.created_at)} ago"
= link_to 'Create New Fleet', new_fleet_path

app/views/fleets/show.html.haml
%div[@fleet]{:data => {:id => @fleet.id, :time => Time.now.to_i, :refresh => 2*1000, :base_url => root_url}}
  .float
    = link_to "Fleet #{@fleet.id}", @fleet, :title => "Copy this URL to invite others to join or to view in your out-of-game browser"
    /= button_to "Copy URL", "#"
  %h3.fleet= @fleet.title
  = render 'details'
  = render 'summary'
  = render 'scouts'
  = render 'reports'
  = render 'recon'
  = render 'pilots'
%ul.navigation
  %li= link_to "Refresh", ""
  - if @current_user && @current_user.in_fleet?(@fleet)
    %li= link_to 'Leave Fleet', leave_path
  - else
    %li= link_to 'Join Fleet', join_url(:id => @fleet)
  %li= link_to 'Delete Fleet', @fleet, :confirm => "Are you sure?", :method => :delete if @fleet.admin?(@current_user)
  %li= link_to 'Fleets', fleets_path