config/routes.rb
FleetTracker::Application.routes.draw do
  match 'fleets/leave' => 'fleets#leave', :as => :leave
  resources :fleets do
    resources :reports
  end
  resources :users

  match 'fleets/:id/join' => 'fleets#join', :as => :join
  match 'about' => 'pages#about'
  match 'env' => 'pages#env'
  match 'ping' => 'users#ping'
  match 'users/:id/tag' => 'tags#create_tag', :as => :create_tag, :via => :post
  match 'users/:id/tag' => 'tags#remove_tag', :as => :remove_tag, :via => :delete
  match 'users/:id/tag' => 'tags#add_tag', :as => :add_tag
  resources :tags do
    get :autocomplete_tag_text, :on => :collection
  end

  root :to => "fleets#index"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  char_name          :string(255)
#  corp_name          :string(255)
#  alliance_name      :string(255)
#  station_name       :string(255)
#  solar_system_name  :string(255)
#  constellation_name :string(255)
#  region_name        :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  fleet_id           :integer
#  changed_at         :datetime
#  tag_id             :integer
#


class User < ActiveRecord::Base
  STALE = 2
  ABANDONED = 10
  PURGE = 20
  
  validates_presence_of :char_name, :corp_name
  validates_uniqueness_of :char_name
  
  before_save :check_for_changes
  
  belongs_to :fleet, :counter_cache => true
  belongs_to :tag

  default_scope :order => 'char_name'
  
  scope :abandoned, lambda {
    where("fleet_id IS NOT NULL and updated_at < ?", ABANDONED.minutes.ago)
  }

  scope :stale, lambda {
    where("fleet_id IS NOT NULL and updated_at < ?", STALE.minutes.ago)
  }

  scope :to_be_purged, lambda {
    where("fleet_id IS NOT NULL and updated_at < ?", PURGE.minutes.ago)
  }
  
  scope :tagged, where("tag_id IS NOT NULL")

  def tag=(tag)
    # TODO Should check if tag is actually changed
    # increments even if user is not saved
    if tag
      self.tag_id = tag.id
      tag.increment!(:usage_count)
    else
      self.tag_id = nil
    end
    return tag
  end
  
  def in_fleet?(fleet)
    fleet_id == fleet.id
  end
  
  def join_fleet(fleet)
    self.fleet = fleet
    self.tag = nil # Shouldn't be necessary
    save
  end
  
  def leave_fleet
    self.fleet = nil
    self.tag = nil
    save
  end

  def set_from_env(env)
    # set everything just in case member has changed corp, etc.
    self.corp_name = env["HTTP_EVE_CORPNAME"]
    self.alliance_name = env["HTTP_EVE_ALLIANCENAME"]
    self.region_name = env["HTTP_EVE_REGIONNAME"]
    self.constellation_name = env["HTTP_EVE_CONSTELLATIONNAME"]
    self.solar_system_name = env["HTTP_EVE_SOLARSYSTEMNAME"]
    self.station_name = env["HTTP_EVE_STATIONNAME"]
  end
  
  def self.find_or_initialize_from_env(env)
    if !env["HTTP_EVE_CHARNAME"].blank?
      user = User.find_or_initialize_by_char_name(env["HTTP_EVE_CHARNAME"])
    end
  end
  
  def self.new_or_update_from_env(env)
    if !env["HTTP_EVE_CHARNAME"].blank?
      user = User.find_or_initialize_by_char_name(env["HTTP_EVE_CHARNAME"])
      user.set_from_env(env)
    end
    return user
  end
  
  def self.new_or_update_from_env_and_save(env)
    if !env["HTTP_EVE_CHARNAME"].blank?
      user = User.find_or_initialize_by_char_name(env["HTTP_EVE_CHARNAME"])
      user.set_from_env(env)
      user.updated_at = Time.now # To force an update
      user.save
      #Logger.new(STDOUT).info('updated user')
    end
    return user
  end
  
  def stale?
    updated_at < STALE.minute.ago
  end
  
  def abandoned?
    updated_at < ABANDONED.minutes.ago
  end
  
  def check_for_changes
    self.changed_at = Time.now if self.solar_system_name_changed? || self.tag_id_changed? || self.fleet_id_changed?
  end
  
  def global_admin?
    return true if (GlobalAdmin.find_by_char_name(self.char_name))
  end
  
  def self.purge
    users = User.to_be_purged
    users.map(&:leave_fleet)
    return users
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_current_user, :except => [:ping]
  before_filter :require_global_admin, :except => [:ping, :show] # show has it's own auth check
  # TODO Check for valid user ID

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    
    if (@current_user && @current_user.global_admin?) || (@user.fleet && @user.fleet.admin?(@current_user) || @user == @current_user)
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    else
      flash[:error] = "You are not authorized to view this user."
      redirect_to root_path
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    if request.env["HTTP_EVE_TRUSTED"]
      @user.set_from_env(request.env)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  # GET /ping.html
  # GET /ping.js
  def ping
    get_current_user_and_force_update
    
    respond_to do |format|
      format.html { render @curent_user_changed ? 'ping_unchanged' : 'ping' }
      format.js
    end
  end
  
  # POST /users/purge
  # def purge
  #   @users = User.abondoned.map(&:destroy)
  # end

  protected
  def fleet_admin
    unless global_admin? || (@user.fleet && @user.fleet.admin?(@current_user))
      flash[:error] = "You are not authorized."
      redirect_to root_path
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :char_name %><br />
    <%= f.text_field :char_name %>
  </div>
  <div class="field">
    <%= f.label :corp_name %><br />
    <%= f.text_field :corp_name %>
  </div>
  <div class="field">
    <%= f.label :alliance_name %><br />
    <%= f.text_field :alliance_name %>
  </div>
  <div class="field">
    <%= f.label :station_name %><br />
    <%= f.text_field :station_name %>
  </div>
  <div class="field">
    <%= f.label :solar_system_name %><br />
    <%= f.text_field :solar_system_name %>
  </div>
  <div class="field">
    <%= f.label :constellation_name %><br />
    <%= f.text_field :constellation_name %>
  </div>
  <div class="field">
    <%= f.label :region_name %><br />
    <%= f.text_field :region_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.haml
.user{ user.stale? ? {:class => "stale"} : {}, user.abandoned? ? {:class => "abandoned"} : {}}
  .pilot= link_to user.char_name, user
  .tag
    - if user.tag
      - if @fleet.admin?(@current_user)
        = link_to(user.tag.text.html_safe + content_tag(:span, "", :class=>"icon"), remove_tag_path(user), :method => :delete, :class=>"tag_link", :title=>"Remove #{user.tag.text} tag from #{user.char_name}")
      - else
        = user.tag.text
    - else
      &nbsp;
      - if @fleet.admin?(@current_user)
        = link_to("Add tag".html_safe + content_tag(:span, "", :class=>"icon"), add_tag_path(user), :title => "Add Tag to #{user.char_name}", :class => "popup add_tag") 
  .corp= user.corp_name
  .alliance= user.alliance_name
  .system
    = user.solar_system_name
    = (user.stale? ? link_to("*", "#", :title => "User has not updated their location in over a minute") : "")

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Char name</th>
    <th>Corp name</th>
    <th>Alliance name</th>
    <th>Station name</th>
    <th>Solar system name</th>
    <th>Constellation name</th>
    <th>Region name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr class="user" id="user_<%= user.id %>">
    <td><%= user.char_name %></td>
    <td><%= user.corp_name %></td>
    <td><%= user.alliance_name %></td>
    <td class="station"><%= user.station_name %></td>
    <td class="system"><%= user.solar_system_name %></td>
    <td><%= user.constellation_name %></td>
    <td><%= user.region_name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/ping.html.haml
%div[@user]
  = "#{@user.char_name} -> #{@user.solar_system_name}"

app/views/users/ping_unchanged.html.haml
%div[@user]
  = "#{@user.char_name} hasn't moved"

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Char name:</b>
  <%= @user.char_name %>
</p>

<p>
  <b>Corp name:</b>
  <%= @user.corp_name %>
</p>

<p>
  <b>Alliance name:</b>
  <%= @user.alliance_name %>
</p>

<p>
  <b>Station name:</b>
  <%= @user.station_name %>
</p>

<p>
  <b>Solar system name:</b>
  <%= @user.solar_system_name %>
</p>

<p>
  <b>Constellation name:</b>
  <%= @user.constellation_name %>
</p>

<p>
  <b>Region name:</b>
  <%= @user.region_name %>
</p>

<p>
  <b>Last Updated:</b>
  <%= time_ago_in_words(@user.updated_at) %> ago <%= @user.stale? ? "[Stale]" : "" %> <%= @user.abandoned? ? "[Abandoned]" : "" %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Users', users_path %> |
<%= link_to 'Fleets', fleets_path %>