config/routes.rb
FleetTracker::Application.routes.draw do
  match 'fleets/leave' => 'fleets#leave', :as => :leave
  resources :fleets do
    resources :reports
  end
  resources :users

  match 'fleets/:id/join' => 'fleets#join', :as => :join
  match 'about' => 'pages#about'
  match 'env' => 'pages#env'
  match 'ping' => 'users#ping'
  match 'users/:id/tag' => 'tags#create_tag', :as => :create_tag, :via => :post
  match 'users/:id/tag' => 'tags#remove_tag', :as => :remove_tag, :via => :delete
  match 'users/:id/tag' => 'tags#add_tag', :as => :add_tag
  resources :tags do
    get :autocomplete_tag_text, :on => :collection
  end

  root :to => "fleets#index"

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id          :integer         not null, primary key
#  text        :string(255)     not null
#  usage_count :integer         not null
#  favorite    :boolean
#  created_at  :datetime
#  updated_at  :datetime
#


class Tag < ActiveRecord::Base
  validates_presence_of :text
  
  has_many :users
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # TODO restrict to fleet admins
  # before_filter :fleet_admin
  # TODO Check or valid user ID
  autocomplete :tag, :text, :full => true

  # GET /users/1/tag
  def add_tag
    @user = User.find(params[:id])
    @tag = Tag.new
  end

  # POST /users/1/tag
  # POST /users/1/tag.xml
  def create_tag
    # TODO could validate that user is in a fleet first
    @user = User.find(params[:id])
    @tag = Tag.find_or_create_by_text(params[:tag][:text])
    @user.tag = @tag

    respond_to do |format|
      if @tag.save
        @user.save
        format.html { redirect_to((@user.fleet ? @user.fleet : @user), :notice => 'Tag was added successfully.') }
        format.xml  { render :xml => @taq, :status => :created, :location => @tag }
      else
        format.html { render :action => "add_tag", :error => "Tag was not added" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1/tag
  # DELETE /users/1/tag.xml
  def remove_tag
    @user = User.find(params[:id])
    @user.tag = nil
    @user.save
    respond_to do |format|
      format.html { redirect_to(@user.fleet) }
      format.xml  { head :ok }
    end
  end

end

app/views/tags/_form.html.haml
= form_for(@tag, :url => create_tag_url(@user), :method => :post) do |f|
  - if @tag.errors.any?
    #error_explanation
      %h3= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg
  .field
    /= f.text_field :text, :placeholder => "e.g. Skirmisher, Scout +2, Squad 1", :size => 40
    = f.autocomplete_field :text, autocomplete_tag_text_tags_path, :placeholder => "e.g. Skirmisher, Scout +2, Squad 1", :size => 30
  .actions
    = f.submit "OK"

app/views/tags/add_tag.html.haml
%h2 Add Tag to #{@user.char_name}
= render 'form'
= link_to 'Back', @user.fleet