config/routes.rb
FleetTracker::Application.routes.draw do
  match 'fleets/leave' => 'fleets#leave', :as => :leave
  resources :fleets do
    resources :reports
  end
  resources :users

  match 'fleets/:id/join' => 'fleets#join', :as => :join
  match 'about' => 'pages#about'
  match 'env' => 'pages#env'
  match 'ping' => 'users#ping'
  match 'users/:id/tag' => 'tags#create_tag', :as => :create_tag, :via => :post
  match 'users/:id/tag' => 'tags#remove_tag', :as => :remove_tag, :via => :delete
  match 'users/:id/tag' => 'tags#add_tag', :as => :add_tag
  resources :tags do
    get :autocomplete_tag_text, :on => :collection
  end

  root :to => "fleets#index"

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                :integer         not null, primary key
#  char_name         :string(255)
#  solar_system_name :string(255)
#  reds              :integer
#  neutrals          :integer
#  created_at        :datetime
#  updated_at        :datetime
#  fleet_id          :integer
#

class Report < ActiveRecord::Base
  validates_presence_of :char_name, :solar_system_name
    
  belongs_to :fleet
  
  default_scope :order => 'updated_at DESC'

  def reds?
    return false if reds.nil?
    reds > 0
  end
  
  def neutrals?
    return false if neutrals.nil?
    neutrals > 0
  end
  
  def clear?
    !reds? && !neutrals?
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :get_current_user
  before_filter :require_igb, :only => [:create]  
  before_filter :require_global_admin, :except => [:create]
  
  # TODO Remove extraneous actions

  # GET /fleet/:fleet_id/reports
  # GET /fleet/:fleet_id/reports.xml
  # GET /fleet/:fleet_id/reports.js
  def index
    @fleet = Fleet.find(params[:fleet_id])
    @reports = @fleet.reports
    if params[:after]
      @reports = @reports.where("updated_at > ?", Time.at(params[:after].to_i + 1))
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
      format.js  { render @fleets }
    end
  end

  # GET /fleet/:fleet_id/reports/1
  # GET /fleet/:fleet_id/reports/1.xml
  def show
    @fleet = Fleet.find(params[:fleet_id])
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /fleet/:fleet_id/reports/new
  # GET /fleet/:fleet_id/reports/new.xml
  def new
    @fleet = Fleet.find(params[:fleet_id])
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /fleet/:fleet_id/reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /fleet/:fleet_id/reports
  # POST /fleet/:fleet_id/reports.xml
  def create
    @fleet = Fleet.find(params[:fleet_id])
    # @report = @fleet.reports.create(params[:report])
    @report = @fleet.reports.
                find_or_create_by_fleet_id_and_solar_system_name(@fleet.id, 
                                                                 @current_user.solar_system_name)
    @report.char_name = @current_user.char_name
    @report.reds = params[:report][:reds] if params[:report][:reds]
    @report.neutrals = params[:report][:neutrals] if params[:report][:neutrals]

    respond_to do |format|
      if @report.save
        format.html { redirect_to(@fleet, :notice => 'Report was successfully created.') }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { redirect_to(@fleet, :error => 'Error creating report!') }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fleet/:fleet_id/reports/1
  # PUT /fleet/:fleet_id/reports/1.xml
  def update
    @fleet = Fleet.find(params[:fleet_id])
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to(@report, :notice => 'Report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fleet/:fleet_id/reports/1
  # DELETE /fleet/:fleet_id/reports/1.xml
  def destroy
    @fleet = Fleet.find(params[:fleet_id])
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def report_in_words(r)
    out = "#{r.char_name} in #{r.solar_system_name}"
    out += ", " + pluralize(r.reds,"red") unless (r.reds.nil? || r.reds==0)
    out += ", " + pluralize(r.neutrals, "neut") unless (r.neutrals.nil? || r.neutrals==0)
    out += ", clear" if r.clear?
    #out += "#{time_ago_in_words(r.updated_at)} ago"
    return out
  end
end

app/views/reports/_form.html.erb
<%= form_for [@fleet, @report] do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>f.hidden_field :fleet_id</div>

  <div class="field">
    <%= f.label :char_name %><br />
    <%= f.text_field :char_name %>
  </div>
  <div class="field">
    <%= f.label :solar_system_name %><br />
    <%= f.text_field :solar_system_name %>
  </div>
  <div class="field">
    <%= f.label :reds %><br />
    <%= f.text_field :reds %>
  </div>
  <div class="field">
    <%= f.label :neutrals %><br />
    <%= f.text_field :neutrals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_report.html.haml
%tr.report{:data => {:time => "#{report.updated_at.to_i}", 
                     :id => "#{report.solar_system_name}"}}
  %td= report_in_words(report)
  %td= timeago(report.updated_at)

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
    <th>Char name</th>
    <th>Solar system name</th>
    <th>Reds</th>
    <th>Neutrals</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.char_name %></td>
    <td><%= report.solar_system_name %></td>
    <td><%= report.reds %></td>
    <td><%= report.neutrals %></td>
    <td><%= link_to 'Show', [@fleet,report] %></td>
    <td><%= link_to 'Edit', edit_fleet_report_path(@fleet,report) %></td>
    <td><%= link_to 'Destroy', [@fleet,report], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_fleet_report_path %>
<%= link_to 'Back', fleet_path(@fleet) %>

app/views/reports/index.js.erb
<% unless @reports.empty? %>
  <% @reports.each do |r| %>
    $(".report[data-id='<%= r.solar_system_name%>']").remove();
  <% end %>
  $("#reports").prepend($("<%= raw escape_javascript(render(@reports))%>").hide().fadeIn('slow'));
<% end %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', fleet_reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Char name:</b>
  <%= @report.char_name %>
</p>

<p>
  <b>Solar system name:</b>
  <%= @report.solar_system_name %>
</p>

<p>
  <b>Reds:</b>
  <%= @report.reds %>
</p>

<p>
  <b>Neutrals:</b>
  <%= @report.neutrals %>
</p>


<%= link_to 'Edit', edit_fleet_report_path(@fleet,@report) %> |
<%= link_to 'Back', fleet_reports_path(@fleet) %>